Repository rhartlage10/CtrlAltElite-Craft, pull requests merged in 2022-04, with the labels that each got.

#44 Updated textures to close issue #42 and #10
  textures/texture.png
Labels: User Story, task

#46 implemented GoogleTest with CMake, closes #40
  CMakeLists.txt
  Sounds/jumpsoundeffect.mp3
Labels: task

#47 added test cases, closes #39
  CMakeLists.txt
  tests/tests.cpp
Labels: User Story
